### PR TITLE
add magic crawl

### PR DESCRIPTION
**Pull request by maddias93**

### CODE REVIEW

**Comment by burned42** [comment]
@maddias93 do you maybe also want to add a description of your game and a list of contributors. If you want you can also add a screenshot like some of the other games :)

**Comment by mychecknix** [comment]
@maddias93 would be nice to have description and a screenshot, that we can publish it.

**Comment by maddias93** [comment]
@burned42 done

**Comment by burned42** [comment]
Great, thanks :) That was the last one I think, the list of games is now complete :tada:

**Pull request merged**
